2023-04-01T01:38:35.5752685Z ##[group]Run actions/setup-python@v4
2023-04-01T01:38:35.5752936Z with:
2023-04-01T01:38:35.5753135Z   python-version: 3.8
2023-04-01T01:38:35.5753341Z   architecture: x64
2023-04-01T01:38:35.5753534Z   cache: pip
2023-04-01T01:38:35.5753729Z   check-latest: false
2023-04-01T01:38:35.5754047Z   token: ***
2023-04-01T01:38:35.5754249Z   update-environment: true
2023-04-01T01:38:35.5754466Z ##[endgroup]
2023-04-01T01:38:35.7439338Z ##[group]Installed versions
2023-04-01T01:38:35.7522574Z Successfully set up CPython (3.8.16)
2023-04-01T01:38:35.7523420Z ##[endgroup]
2023-04-01T01:38:36.1773506Z [command]/opt/hostedtoolcache/Python/3.8.16/x64/bin/pip cache dir
2023-04-01T01:38:36.5205370Z /home/runner/.cache/pip
2023-04-01T01:38:37.5093738Z Received 6243437 of 6243437 (100.0%), 13.8 MBs/sec
2023-04-01T01:38:37.5095048Z Cache Size: ~6 MB (6243437 B)
2023-04-01T01:38:37.5116357Z [command]/usr/bin/tar -z -xf /home/runner/work/_temp/f8cb5278-a1de-46bc-864b-81a1cfe4cacd/cache.tgz -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A
2023-04-01T01:38:37.5721096Z Cache restored successfully
2023-04-01T01:38:37.5736212Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.16-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
