2023-04-19T01:38:16.5478572Z ##[group]Run actions/setup-python@v4
2023-04-19T01:38:16.5478814Z with:
2023-04-19T01:38:16.5479013Z   python-version: 3.8
2023-04-19T01:38:16.5479226Z   architecture: x64
2023-04-19T01:38:16.5479419Z   cache: pip
2023-04-19T01:38:16.5479608Z   check-latest: false
2023-04-19T01:38:16.5479921Z   token: ***
2023-04-19T01:38:16.5480127Z   update-environment: true
2023-04-19T01:38:16.5480339Z ##[endgroup]
2023-04-19T01:38:16.7236910Z ##[group]Installed versions
2023-04-19T01:38:16.7326633Z Successfully set up CPython (3.8.16)
2023-04-19T01:38:16.7327483Z ##[endgroup]
2023-04-19T01:38:17.1760793Z [command]/opt/hostedtoolcache/Python/3.8.16/x64/bin/pip cache dir
2023-04-19T01:38:19.6349447Z /home/runner/.cache/pip
2023-04-19T01:38:19.9528921Z Received 6243437 of 6243437 (100.0%), 53.6 MBs/sec
2023-04-19T01:38:19.9529620Z Cache Size: ~6 MB (6243437 B)
2023-04-19T01:38:19.9549944Z [command]/usr/bin/tar -z -xf /home/runner/work/_temp/1b23620d-29ca-4e49-9c42-2fa1e1a3a654/cache.tgz -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A
2023-04-19T01:38:20.0152224Z Cache restored successfully
2023-04-19T01:38:20.0167041Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.16-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
