2024-02-02T00:22:57.9385944Z ##[group]Run actions/setup-python@v4
2024-02-02T00:22:57.9386582Z with:
2024-02-02T00:22:57.9387010Z   python-version: 3.8
2024-02-02T00:22:57.9387377Z   architecture: x64
2024-02-02T00:22:57.9387847Z   cache: pip
2024-02-02T00:22:57.9388197Z   check-latest: false
2024-02-02T00:22:57.9388740Z   token: ***
2024-02-02T00:22:57.9389129Z   update-environment: true
2024-02-02T00:22:57.9389549Z   allow-prereleases: false
2024-02-02T00:22:57.9389956Z ##[endgroup]
2024-02-02T00:22:58.0839683Z ##[group]Installed versions
2024-02-02T00:22:58.0913035Z Successfully set up CPython (3.8.18)
2024-02-02T00:22:58.0914427Z ##[endgroup]
2024-02-02T00:22:59.0272878Z [command]/opt/hostedtoolcache/Python/3.8.18/x64/bin/pip cache dir
2024-02-02T00:22:59.3618563Z /home/runner/.cache/pip
2024-02-02T00:22:59.6946500Z Received 6245959 of 6245959 (100.0%), 41.1 MBs/sec
2024-02-02T00:22:59.6947740Z Cache Size: ~6 MB (6245959 B)
2024-02-02T00:22:59.6975241Z [command]/usr/bin/tar -xf /home/runner/work/_temp/9d4114e3-8f81-4d79-8f8b-27dade57b82b/cache.tzst -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A --use-compress-program unzstd
2024-02-02T00:22:59.7257675Z Cache restored successfully
2024-02-02T00:22:59.7281430Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.18-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
