2023-04-03T01:34:38.8535534Z ##[group]Run actions/setup-python@v4
2023-04-03T01:34:38.8536071Z with:
2023-04-03T01:34:38.8536298Z   python-version: 3.8
2023-04-03T01:34:38.8536527Z   architecture: x64
2023-04-03T01:34:38.8536750Z   cache: pip
2023-04-03T01:34:38.8536978Z   check-latest: false
2023-04-03T01:34:38.8537395Z   token: ***
2023-04-03T01:34:38.8537627Z   update-environment: true
2023-04-03T01:34:38.8537873Z ##[endgroup]
2023-04-03T01:34:39.0610965Z ##[group]Installed versions
2023-04-03T01:34:39.0744855Z Successfully set up CPython (3.8.16)
2023-04-03T01:34:39.0745878Z ##[endgroup]
2023-04-03T01:34:39.8260121Z [command]/opt/hostedtoolcache/Python/3.8.16/x64/bin/pip cache dir
2023-04-03T01:34:40.4154259Z /home/runner/.cache/pip
2023-04-03T01:34:42.0492744Z Received 0 of 6243437 (0.0%), 0.0 MBs/sec
2023-04-03T01:34:42.1238701Z Received 6243437 of 6243437 (100.0%), 5.5 MBs/sec
2023-04-03T01:34:42.1243433Z Cache Size: ~6 MB (6243437 B)
2023-04-03T01:34:42.1330701Z [command]/usr/bin/tar -z -xf /home/runner/work/_temp/88997e8d-8122-48cf-a5ae-439266f5f3cf/cache.tgz -P -C /home/runner/work/GitHub_Stats_A/GitHub_Stats_A
2023-04-03T01:34:42.1972908Z Cache restored successfully
2023-04-03T01:34:42.1992440Z Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.8.16-pip-60f2a6c0212a9b74a155cd81b58dd07fd8b180833132566260d95f4de42fe218
